boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S x86_desc.h types.h
syscall.o: syscall.S
x86_desc.o: x86_desc.S x86_desc.h types.h
defaultcall.o: defaultcall.c defaultcall.h types.h
filesystem.o: filesystem.c filesystem.h types.h systemcall.h lib.h \
  terminal.h keyboard.h i8259.h page.h x86_desc.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h terminal.h keyboard.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h
IDT.o: IDT.c IDT.h x86_desc.h types.h i8259.h keyboard.h lib.h terminal.h \
  page.h systemcall.h filesystem.h rtc.h idt_linkage.h PIT.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h terminal.h \
  keyboard.h i8259.h page.h systemcall.h filesystem.h rtc.h IDT.h \
  idt_linkage.h PIT.h debug.h tests.h
keyboard.o: keyboard.c keyboard.h types.h lib.h terminal.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h i8259.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h
page.o: page.c lib.h types.h terminal.h keyboard.h i8259.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h
PIT.o: PIT.c PIT.h types.h lib.h terminal.h keyboard.h i8259.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h
rtc.o: rtc.c rtc.h types.h lib.h terminal.h keyboard.h i8259.h page.h \
  systemcall.h filesystem.h x86_desc.h
systemcall.o: systemcall.c systemcall.h lib.h types.h terminal.h \
  keyboard.h i8259.h page.h filesystem.h x86_desc.h rtc.h defaultcall.h
terminal.o: terminal.c terminal.h types.h lib.h keyboard.h i8259.h page.h \
  systemcall.h filesystem.h x86_desc.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h keyboard.h \
  i8259.h page.h systemcall.h filesystem.h rtc.h
